import keyboard as keyb
import time
print("██████╗░██╗░░░░░░██████╗")
print("██╔══██╗██║░░░░░██╔════╝")
print("██████╔╝██║░░░░░╚█████╗░")
print("██╔═══╝░██║░░░░░░╚═══██╗")
print("██║░░░░░███████╗██████╔╝")
print("╚═╝░░░░░╚══════╝╚═════╝░")
print("█▀▄ █▀█ █▄░█ ▄▀█ ▀█▀ █▀▀   █▀▀ ▄▀█ █▀█ █▀▄▀█")
print("█▄▀ █▄█ █░▀█ █▀█ ░█░ ██▄   █▀░ █▀█ █▀▄ █░▀░█")
print("🇧​​​​​🇾​​​​​ 🇰​​​​​🇦​​​​​🇫​​​​​🇺​​​​​🇳​​​​​.🇷​​​​​🇺​​​​​")
print("For start press Q!")
keyb.wait('q')

print("S𝜏αɾ𝜏 Ƒαɾ𝓶ιɳց!")
while True:
    keyb.press('space')
    time.sleep(2)
    keyb.release('space')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.5)
    keyb.release('w')
    time.sleep(2)
    keyb.press('s')
    time.sleep(0.6)
    keyb.release('s')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.1)
    keyb.release('w')
    time.sleep(0.5)
    keyb.press('/')
    time.sleep(0.5)
    keyb.release('/')
    time.sleep(0.5)
    keyb.write('/e dance')
    time.sleep(0.5)
    keyb.press('enter')
    time.sleep(0.5)
    keyb.release('enter')
    time.sleep(20)
    keyb.press('space')
    time.sleep(2)
    keyb.release('space')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.5)
    keyb.release('w')
    time.sleep(2)
    keyb.press('s')
    time.sleep(0.6)
    keyb.release('s')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.1)
    keyb.release('w')
    time.sleep(0.5)
    keyb.press('/')
    time.sleep(0.5)
    keyb.release('/')
    time.sleep(0.5)
    keyb.write('/e dance')
    time.sleep(0.5)
    keyb.press('enter')
    time.sleep(0.5)
    keyb.release('enter')
    time.sleep(20)
    keyb.press('space')
    time.sleep(2)
    keyb.release('space')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.5)
    keyb.release('w')
    time.sleep(2)
    keyb.press('s')
    time.sleep(0.6)
    keyb.release('s')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.1)
    keyb.release('w')
    time.sleep(0.5)
    keyb.press('/')
    time.sleep(0.5)
    keyb.release('/')
    time.sleep(0.5)
    keyb.write('/e dance')
    time.sleep(0.5)
    keyb.press('enter')
    time.sleep(0.5)
    keyb.release('enter')
    time.sleep(20)
    keyb.press('space')
    time.sleep(2)
    keyb.release('space')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.5)
    keyb.release('w')
    time.sleep(2)
    keyb.press('s')
    time.sleep(0.6)
    keyb.release('s')
    time.sleep(2)
    keyb.press('w')
    time.sleep(0.1)
    keyb.release('w')
    time.sleep(0.5)
    keyb.press('/')
    time.sleep(0.5)
    keyb.release('/')
    time.sleep(0.5)
    keyb.write('/e dance')
    time.sleep(0.5)
    keyb.press('enter')
    time.sleep(0.5)
    keyb.release('enter')
    time.sleep(20)
    keyb.press('/')
    time.sleep(0.5)
    keyb.release('/')
    time.sleep(0.5)
    keyb.write('Please! Look on my gamepasses! I made them for a long time :3')
    time.sleep(0.5)
    keyb.press('enter')
    time.sleep(0.5)
    keyb.release('enter')
    time.sleep(20)



    
    
    


keyb.wait()

